// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhY2hQFlCa7GV1VwswFUyWhdXVkNNg6_s',
    appId: '1:955567105939:web:e4a0541c82f57c7df4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    authDomain: 'shopit-e2861.firebaseapp.com',
    storageBucket: 'shopit-e2861.firebasestorage.app',
    measurementId: 'G-11F36TPPC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYhsrCR7UXWVj2i5mpt4sEy-RmZbPuHk',
    appId: '1:955567105939:android:6537d599bd340fb7f4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    storageBucket: 'shopit-e2861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxF_FK-MSU8hmvwfME5smxvMxORlLamRM',
    appId: '1:955567105939:ios:63a660b2e40d9efcf4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    storageBucket: 'shopit-e2861.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxF_FK-MSU8hmvwfME5smxvMxORlLamRM',
    appId: '1:955567105939:ios:63a660b2e40d9efcf4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    storageBucket: 'shopit-e2861.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhY2hQFlCa7GV1VwswFUyWhdXVkNNg6_s',
    appId: '1:955567105939:web:1f0b8a7efd292f50f4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    authDomain: 'shopit-e2861.firebaseapp.com',
    storageBucket: 'shopit-e2861.firebasestorage.app',
    measurementId: 'G-QL6C2VQBJB',
  );
}
