// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2jGnFujttycEpr6dAZrv0ha6RFf1CgE',
    appId: '1:748992448443:web:6c40e18a9646f488b6669e',
    messagingSenderId: '748992448443',
    projectId: 'shopit-da8dd',
    authDomain: 'shopit-da8dd.firebaseapp.com',
    storageBucket: 'shopit-da8dd.firebasestorage.app',
    measurementId: 'G-VD97EKK03S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEeNk76zyLHd3d_gXhJWkx4mDCbV2oeM',
    appId: '1:748992448443:android:55ab9cdee8550009b6669e',
    messagingSenderId: '748992448443',
    projectId: 'shopit-da8dd',
    storageBucket: 'shopit-da8dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQM2Wc8mOGt8z01UVSc4rTfDzp49Hxybw',
    appId: '1:748992448443:ios:72e511eba8581cfab6669e',
    messagingSenderId: '748992448443',
    projectId: 'shopit-da8dd',
    storageBucket: 'shopit-da8dd.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxF_FK-MSU8hmvwfME5smxvMxORlLamRM',
    appId: '1:955567105939:ios:63a660b2e40d9efcf4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    storageBucket: 'shopit-e2861.firebasestorage.app',
    iosBundleId: 'com.example.shopit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhY2hQFlCa7GV1VwswFUyWhdXVkNNg6_s',
    appId: '1:955567105939:web:1f0b8a7efd292f50f4aa66',
    messagingSenderId: '955567105939',
    projectId: 'shopit-e2861',
    authDomain: 'shopit-e2861.firebaseapp.com',
    storageBucket: 'shopit-e2861.firebasestorage.app',
    measurementId: 'G-QL6C2VQBJB',
  );

}